sudo: false
language: cpp

compiler:
  - clang
  - g++

addons:
  apt: 
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8 
      - g++-4.8
      - clang-3.5
      - valgrind
      - libgtest-dev
      - libstdc++-4.8-dev
      - libboost-dev

install:
  # install gtest without sudo
  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cp -r /usr/src/gtest/* ./
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - cd -
  # Correct gcc version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - make
  - make run_tests
  - make run_valgrind_tests
