sudo: false
language: cpp

compiler:
  - clang
  - gcc

addons:
  apt: 
   sources: 
      - ubuntu-toolchain-r-test
   packages:
      - gcc-4.8 
      - g++-4.8
      - clang-3.5
      - doxygen
      - valgrind
      - libgtest-dev
      - libboost-dev

install:
    # Install gtest without sudo 
    - mkdir ~/gtest && cd ~/gtest
    - export LIBRARY_PATH=$(pwd)
    - cp -r /usr/src/gtest/* ./
    - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
    - make
    - cd -


script:
 - make run_tests
 - make run_valgrind_tests
