sudo: false
language: cpp

compiler:
  - clang
  - g++

env:
  - COVERAGE=true

addons:
  apt: 
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8 
      - g++-4.8
      - clang-3.5
      - doxygen
      - valgrind
      - libgtest-dev
      - libboost-dev
      - libstdc++-4.8-dev
      - python2.7
      - python-pip

install:
  # Install gtest without sudo 
  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cp -r /usr/src/gtest/* ./
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - cd -
  # Use correct g++ version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Install gcovr
  # - export PATH=$HOME/.local/bin:$PATH
  # - pip install --user gcovr

script:
  - make run_tests
  - make run_valgrind_tests
  # - make coverage

